apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.13
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.49
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http