apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.13
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
  revisionHistoryLimit: 5
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: 
      partition: 0
  podManagementPolicy: Parallel
  serviceName: authelia
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: authelia
        app.kubernetes.io/instance: authelia
        app.kubernetes.io/version: 4.39.13
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: authelia-0.10.49
      annotations:
        authelia.com/checksum-config: f4cdab7119f5f61b0ef18586d72b3fb741470502cdb87ceb14dafd867b332715
        authelia.com/checksum-secret: 83bb3ece24f1a6abfa0039cc1e581d7d6067c6d908fb8b2abe46fc5ad4dfc6fe
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity: 
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      enableServiceLinks: false
      containers:
      - name: authelia
        image: ghcr.io/authelia/authelia:4.39.13
        imagePullPolicy: IfNotPresent
        command:
        - 'authelia'
        resources: 
          limits: {}
          requests: {}
        env:
        - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
          value: "true"
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
          value: '/secrets/internal/identity_validation.reset_password.jwt.hmac.key'
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: '/secrets/internal/session.encryption.key'
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: '/secrets/internal/storage.encryption.key'
        - name: X_AUTHELIA_CONFIG
          value: '/configuration.yaml'
        - name: X_AUTHELIA_CONFIG_FILTERS
          value: template
        - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: smtp-password
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /configuration.yaml
          subPath: configuration.yaml
          readOnly: true
        - name: secrets
          mountPath: /secrets/internal
          readOnly: true
        - mountPath: /config/users
          name: users-database
          readOnly: true
        - mountPath: /config/smtp
          name: smtp-password
          readOnly: true
        - mountPath: /secrets/oidc
          name: oidc
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: authelia
          items:
          - key: configuration.yaml
            path: configuration.yaml
      - name: secrets
        secret:
          secretName: authelia
          items:
          - key: identity_validation.reset_password.jwt.hmac.key
            path: identity_validation.reset_password.jwt.hmac.key
          - key: session.encryption.key
            path: session.encryption.key
          - key: storage.encryption.key
            path: storage.encryption.key
      - name: users-database
        configMap:
          name: authelia-users
          items:
          - key: users-database.yml
            path: users_database.yml
      - name: smtp-password
        secret:
          secretName: smtp-password
          items:
          - key: password.txt
            path: password.txt
      - name: oidc
        secret:
          secretName: jwk-cert-secret
          items:
          - key: jwk.RS256.pem
            path: jwk.RS256.pem