kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: litellm-postgresql
  namespace: "litellm"
  labels:
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 18.1.0
    helm.sh/chart: postgresql-18.2.0
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: litellm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5432