apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-certificate
  namespace: kube-system
spec:
  commonName: "eheaver.cloud"
  secretName: default-ingress-cert
  privateKey:
    rotationPolicy: "Never"
  issuerRef:
    name: internal-cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "eheaver.cloud"
    - "*.eheaver.cloud"
    - "*.internal.eheaver.cloud"