apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-redis
  namespace: open-webui
  labels:
    app.kubernetes.io/version: "0.7.2"
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-redis
  annotations: {}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-webui
      app.kubernetes.io/component: open-webui-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "0.7.2"
        app.kubernetes.io/name: open-webui
        app.kubernetes.io/instance: open-webui
        app.kubernetes.io/component: open-webui-redis
      annotations: {}
    spec:
      containers:
      - name: open-webui-redis
        image: "redis:7.4.2-alpine3.21"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 6379
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi