apiVersion: v1
kind: Service
metadata:
  name: open-webui-redis
  namespace: open-webui
  labels:
    app.kubernetes.io/version: "0.7.2"
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-redis
  annotations: {}
spec:
  selector:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-redis
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 6379
    targetPort: http