apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/headless-postgres-service.yaml
- ./resources/networking-policy.yaml
- ./resources/postgres-statefulset.yaml
- ./resources/service-account.yaml
- ./resources/pdb.yaml
- ./secrets/sealed-db-access.yaml
- ./secrets/sealed-db-creds.yaml