apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-postgresql
  namespace: "litellm"
  labels:
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 18.1.0
automountServiceAccountToken: false