apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: litellm
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/version: "main-v1.80.11-stable"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
      app.kubernetes.io/instance: litellm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/instance: litellm
        app.kubernetes.io/version: "main-v1.80.11-stable"
    spec:
      serviceAccountName: default
      securityContext: {}
      containers:
        - name: litellm
          securityContext: {}
          image: "ghcr.io/berriai/litellm-database:main-v1.80.11-stable"
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4000"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: litellm-dbcredentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-dbcredentials
                  key: password
            - name: DATABASE_HOST
              value: litellm-postgresql
            - name: DATABASE_NAME
              value: litellm
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: PROXY_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-masterkey
                  key: masterkey
            - name: MINIMAX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minimax-key
                  key: api_key
          envFrom: []
          args:
            - --config
            - /etc/litellm/config.yaml
            
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: "http"
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: "http"
          startupProbe:
            httpGet:
              path: /health/readiness
              port: "http"
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

          volumeMounts:
            - name: litellm-config
              mountPath: /etc/litellm/
          
      volumes:
        - name: litellm-config
          configMap:
            name: litellm-config
            items:
              - key: config.yaml
                path: "config.yaml"
      terminationGracePeriodSeconds: 90