apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
      general_settings:
        master_key: os.environ/PROXY_MASTER_KEY
      model_list:
      - model_name: MiniMax-M2.1
        litellm_params:
          model: anthropic/MiniMax-M2.1
          custom_llm_provider: anthropic
          api_key: os.environ/MINIMAX_API_KEY
          api_base: https://api.minimax.io/anthropic
