apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./jobs/migrations-job.yaml
- ./jobs/test-connection-job.yaml
- ./resources/pg/headless-postgres-service.yaml
- ./resources/pg/networking-policy.yaml
- ./resources/pg/postgres-statefulset.yaml
- ./resources/pg/service-account.yaml
- ./resources/main-deployment.yaml
- ./resources/main-service.yaml
- ./resources/pg/pdb.yaml
- ./resources/settings-configmap.yaml
- ./secrets/sealed-db-access.yaml
- ./secrets/sealed-db-creds.yaml
- ./secrets/sealed-masterkey.yaml