apiVersion: batch/v1
kind: Job
metadata:
  name: litellm-migrations
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
    app.kubernetes.io/version: "main-v1.80.11-stable"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litellm
        app.kubernetes.io/instance: litellm
        app.kubernetes.io/version: "main-v1.80.11-stable"
      annotations: {}
    spec:
      serviceAccountName: default
      containers:
        - name: prisma-migrations
          image: "ghcr.io/berriai/litellm-database:main-v1.80.11-stable"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          command: ["python", "litellm/proxy/prisma_migration.py"]
          workingDir: "/app"
          env:
            - name: DATABASE_URL
              value: postgresql://litellm:NoTaGrEaTpAsSwOrD@litellm-postgresql/litellm
            - name: DISABLE_SCHEMA_UPDATE
              value: "false" # always run the migration from the Helm PreSync hook, override the value set
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 120
  backoffLimit: 4