---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minimax-key
  namespace: litellm
spec:
  encryptedData:
    api_key: AgAAao/aDPLUrav/gv+NJxInh4HpCePWA0rYcMYYFL5fMAM5Pwcu3XONQb6XT5vp2k4C4rCK0xUE8mFCq5Yv4NDW/yQsWAiy3pTPFQ9Amz/k0PKK/vpM+BfCCkulM5H7oF5biNosvhX90Ya1JBmCaibXHjvBE8nO5lofGEvG553cLgUZfWdN/O5uXc3d+qMsUP9+j37Fhc/cJKgYqk1naYQAQmXaZJih3uDMjw2scrnA8LTtnfkrlFqcbkremn32tpkItxC3X9LElQDqKyQI9x5vrVobgNADd+Wi8cbUPVc9A1GQgT1dnmoz+aTUk61l6w68cVW/R8MAdaXeI4T240L4OWGFjWeOJIKTyFRP0/8e2b+mhFd0zsxeyvM25MhRw+6vavOs8QJNywAdKPTKS0DoRBx/QvVxH7kR2MCPwRIV/VakRdukfG6g2XmwqagaaDkPNTF0zGim4rDZGrOghooxFc/gH2+Fo89W+Ldemv25quFbV7dv77uLdMggIsvL0tvMiJ0gXAH/Dfp+Qx9zO6kFByWW7CPwZG7NL/xqxGcIwQBA0Yl8Bkih4wEXQIcEamZ76eqQvPkV8XQeAfjK0LbUWV5NtA8x3TryhxMEyPYrqgnzAefZI2TSBfscN3yaIxPDu2sgSBypHb9hZH3GD52ezSp7zK3cc3fGjjxGyML7lErHpGHw2IJ54DUaVorD5hpPJI+8cLqUNIjVnUqzfkHFrWK/548b+KjiEAKW+9tkoGkWfNhkoeRtHoqvvLuqnsR3kKAMH2c9wT1dNUinPDMYmYEqxcL9r5OAh00Zi8C0sICe47QmcPG8Qfj4lN0val7YDBZHDpLPPvh92pKCvQ+KFVbnLiLIysVpKcb+ets=
  template:
    metadata:
      creationTimestamp: null
      name: minimax-key
      namespace: litellm
