apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui-tls
  namespace: open-webui
spec:
  commonName: "eheaver.cloud"
  secretName: open-webui-cert-secret
  privateKey:
    rotationPolicy: "Never"
  issuerRef:
    name: internal-cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "eheaver.cloud"
    - "*.eheaver.cloud"
    - "*.internal.eheaver.cloud"