apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-ir
  namespace: open-webui
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`chat.eheaver.cloud`)
      kind: Rule
      middlewares:
      - name: redirect-https
        namespace: kube-system 
      services:
        - name: open-webui
          kind: Service
          namespace: open-webui
          passHostHeader: true
          port: 8080
  tls: 
    secretName: open-webui-cert-secret
          