apiVersion: v1
kind: ServiceAccount
metadata:
  name: existing-sa
  namespace: open-webui
  labels:
    app.kubernetes.io/version: "0.7.2"
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
automountServiceAccountToken: false