---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-postgresql
  namespace: litellm
spec:
  encryptedData:
    password: AgBOYyDj1Yw4KzF69ca4+QhjKIPZMlgGw1QQvVcDJTAPEdHcsiJmnAf4gTt80ZVs0WrfUQWRhbVmJNRCj/waTskc0ti6AEJBJERECXqJdcDXjYR1izdmdMOgWBWPAZEcU2h7Sq85uHluvMrwY/NmVvM08TeJQyAPOoh0V7TEuDjGMXdgv24RWvQEZ9GzdlJAUY2/j5YGKf9MA4UnqDcOxSFDM9dQgTASnKk4jWQgZ4daz/TvGL6LOHs9+PPtPIp6tRv0oZO24rFiu3k7xS83ejl6aUNMZ0jqeA08MYrRs0xlvOBvbrUN0Q+QbAMKwYAT2Ro51WFKNI2B0Qo1AGfo/G0+tkPiFE3OgFyepVPxPgk1/P3b43kRMef2T7w9BZRC7Mo4B8I+hOQeKJypfPRYfPu0+vR2y6dewi6b1i+9EkmqiREgKinNl1otqshl6GsrGgCs+IcPREO3+sueArqFMW7BC4t7bgPdojGH42M8L5Ak4uN7G2a/DmDPJU9pQinGxxpHaT0x1+YNQ70UI3djpmWh28bmw2XSGpBQoMr1rjGca7a8hAHgwv8phn89NVF3nutpWEHs1/7BHuWZGDlzjsPYOQotb9YTS5SpTVhPXkzXNH+D2RkluV+VE//+nbT9PaiKGE7gQW+o/zjYKfZNz51aZKw1YBx0YXoS3YOtxQYwjIz/ZrEu6e3mrYfPYwd9FTlP9sJAkjMjzQ5v5RH/hrSgLA==
    postgres-password: AgAfnyKl1ZZ8IX0zAZSjUQ+P/BkQOoxgNMX1y8IItoql5VL5R93qhWVmEXQTV3ZXr+Me+AEmi0AOPLhjAHRpHcZ5Et5hFArs4m3E8Lt76vCjvVsgKI/mc/tMgIR5SGwUmHcAqrsdfOzCGVGFwElNkjlVxZt2kRlSJwQvK4WEf3sA1Xb+lSnwpGpZV3vt27fE6V4mtZcnJuAGLQMoAtikaN4vr75RCo92GsUDAyLK8/FCTe8AUW4YHUMMTOc606WEjAoCcn0MU5sq4ElbGrHtudmO3ekvQY1aPsLRsM0+Mu5GOjna+kge0/egsD+PDsOzqTOqRVM+GdYrQHoCH0DiZ+6p+O4UQbJOr4CUGPRa3G70/2uaJeRYq2/B3fivL5K7xsagKdIHhZp/6cq+84Bart7o+AVB8va2i2I2Pov0PeC13+ph7Tz1UAUcWSTmN5U7ayvS6ntp/I/fka/ISHIQ3SRqMJFSxvDXuJe6o9su4IMjbGI2DfU0n6t7jFp1FikkhroSlEfz9uMWdqDin5qf4sLV55f20aOnKgMsli7bvg8Id/7aW53TiUkveIExyZi5B/1e2U5k6m4xmHA82XyeIdC5/nY8sct4faX74c9UrfRVdso4n8xKlH/mSmWH4Q+dkIVx2ZEaHmmXIKTjGEP3AyGg++g147sbnJDtOTfMj/+rjrcaiRXHBTSUV1vZKNKG/4XwIkxwN5f/lPDW
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: litellm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 18.1.0
        helm.sh/chart: postgresql-18.2.0
      name: litellm-postgresql
      namespace: litellm
    type: Opaque
