---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-masterkey
  namespace: litellm
spec:
  encryptedData:
    masterkey: AgAT4cTb4ewly3Ispi2eX3jAJWirhqV0cb7ZMhe2FI4UN39wR1Y0CD0E1p64UDaI2KMZKhdbBXo3SEV21ITNx5JZ2lDGiCDwb3g0WgMyl590tsXW285zEhVD8kbTmUhcwlLkzLiFri39+BvbJ+1W7d7W7wUTKIwbsCzTj1sjfqzGkQL9qTySAW7VNxBO4ZXQyF8+ODUN5mgPQt6AJus+2PP4t0I3RVFYixeNDsxLTw9BU2hy0ceFAVaErCyEcarDwDQUN5VP+RmjwEC++4OJwQI1Y92BDchbBloNCQ+FNDv0Xcpn8bH+59umm+z6IgxuFgLIZfSuQ0OCfMQS1BKyvKeks3z23wKWOSU4gl1az7Wqmksp+sr7pfvl55BFS9pk7fOTcESkJi1Vr2mZAgEamMSrpK/bBKWPlZxUkbv/lIPOrSfutu8cVxmaTD11vqFlHa5vMeFNRWpKwuY6EhYazjDA6BsLasfm0MdA0FoJAt6uSDyG9flT2+IkqPlE7KoOn0+66uYcKl2SkBAnqtOUiO1oKkwBm1jG/OZlO3rfJGZdF0WxIsXaI1AAAmlalg24I0rmjwXpBTx9VSVzk6YwtpmlmZAR8Br/BQm19hD4HE0t6X5avqn2iClzgNHHs6LEmOzXAPbVMQEiHJ7rdoiBsa1VM0aJmlQ2MM+wvsaRhXosV1f0yXVhDJNEO/rvsQONBgnbuSduxyMessXDHfGkWv3OS0zBpu4=
  template:
    metadata:
      creationTimestamp: null
      name: litellm-masterkey
      namespace: litellm
    type: Opaque
