apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s-cluster-config
spec:
  api:
    address: 192.168.100.11
    externalAddress: 192.168.1.162 
    sans:
      - 192.168.1.162
      - 192.168.100.11
      - 192.168.100.1
      - 127.0.0.1
      - 127.0.1.1
  extensions:
    helm:
      repositories:
      - name: traefik
        url: https://traefik.github.io/charts
      charts:
      - name: traefik
        chartname: traefik/traefik
        version: "37.2.0"
        namespace: default
  telemetry:
    enabled: false