apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/authelia-configmap.yaml
- ./resources/authelia-users-configmap.yaml
- ./resources/sealed-authelia-secret.yaml
- ./resources/sealed-jwks-cert.yaml
- ./resources/sealed-smtp.yaml
- ./resources/service.yaml
- ./resources/statefulset.yaml