apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./jobs/test-connection-job.yaml
- ./resources/main-deployment.yaml
- ./resources/main-service.yaml
- ./resources/settings-configmap.yaml
- ./secrets/sealed-db-access.yaml
- ./secrets/sealed-db-creds.yaml
- ./secrets/sealed-masterkey.yaml